baseurl: /
languageCode: en-US
title: Danielle Nguyen
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /post/:year/:month/:day/:slug
params:
  about: I am Biology major with a minor in Educational Psychology. 
  author: Danielle Nguyen
  avatar: profile.JPG
  custom_css: []
  custom_js: []
  occupation: Emergency Medical Technician
  social:
    Email: dtn722@utexas.edu
    Github: dan-guille
menu:
  main:
    - identifier: blog
      name: blog
      url: /post/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300
